export const commentsTypes = {
  FETCH_COMMENTS_REQUEST: 'FETCH_COMMENTS_REQUEST',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
  FETCH_COMMENTS_FAILURE: 'FETCH_COMMENTS_FAILURE',
  FETCH_POST_ITEM_REQUEST: 'FETCH_POST_ITEM_REQUEST',
  FETCH_POST_ITEM_SUCCESS: 'FETCH_POST_ITEM_SUCCESS',
  FETCH_POST_ITEM_FAILURE: 'FETCH_POST_ITEM_FAILURE',
  ADD_NEW_COMMENT: 'ADD_NEW_COMMENT',
  TOGGLE_INPUT: 'TOGGLE_INPUT'
}